export const TEMPLATES = [
  {
    id: 'privacy-policy',
    name: 'Privacy Policy',
    icon: '🔒',
    description: 'A comprehensive privacy policy explaining how you collect, use, and protect user data.',
    fields: [
      { key: 'companyName', label: 'Company / Website Name', placeholder: 'Acme Corp', required: true },
      { key: 'websiteUrl', label: 'Website URL', placeholder: 'https://acme.com', required: true },
      { key: 'contactEmail', label: 'Contact Email', placeholder: 'privacy@acme.com', required: true, type: 'email' },
      { key: 'country', label: 'Country / Jurisdiction', placeholder: 'United States', required: true },
      { key: 'dataTypes', label: 'Types of Data Collected', type: 'textarea', placeholder: 'Name, email address, usage data, IP address…', wide: true, hint: 'List the personal data your site/app collects from users.' },
      { key: 'dataUse', label: 'How Data is Used', type: 'textarea', placeholder: 'To provide services, send newsletters, improve the product…', wide: true },
      { key: 'thirdParties', label: 'Third-Party Services Used', type: 'textarea', placeholder: 'Google Analytics, Stripe, Mailchimp…', wide: true, hint: 'List any analytics, payment, or marketing services that receive user data.' },
      { key: 'cookiesUsed', label: 'Cookies Used?', type: 'select', options: [{ value: 'yes', label: 'Yes — functional and/or analytics cookies' }, { value: 'no', label: 'No cookies used' }, { value: 'essential', label: 'Essential cookies only' }] },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', required: true },
    ],
  },
  {
    id: 'terms-of-service',
    name: 'Terms of Service',
    icon: '📜',
    description: 'Define the rules and expectations for users of your website or application.',
    fields: [
      { key: 'companyName', label: 'Company / Website Name', placeholder: 'Acme Corp', required: true },
      { key: 'websiteUrl', label: 'Website URL', placeholder: 'https://acme.com', required: true },
      { key: 'contactEmail', label: 'Contact Email', placeholder: 'legal@acme.com', required: true, type: 'email' },
      { key: 'country', label: 'Governing Law (State/Country)', placeholder: 'California, United States', required: true },
      { key: 'serviceDescription', label: 'Service Description', type: 'textarea', placeholder: 'A SaaS project management platform…', wide: true, hint: 'Briefly describe what your product or service does.' },
      { key: 'prohibitedUses', label: 'Prohibited Uses', type: 'textarea', placeholder: 'Spamming, illegal activity, scraping without permission…', wide: true },
      { key: 'ageRequirement', label: 'Minimum Age', type: 'select', options: [{ value: '13', label: '13 years old (COPPA)' }, { value: '16', label: '16 years old (GDPR)' }, { value: '18', label: '18 years old' }] },
      { key: 'subscriptionType', label: 'Payment Model', type: 'select', options: [{ value: 'free', label: 'Free / No payment' }, { value: 'one-time', label: 'One-time purchase' }, { value: 'subscription', label: 'Subscription / Recurring billing' }] },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', required: true },
    ],
  },
  {
    id: 'cookie-policy',
    name: 'Cookie Policy',
    icon: '🍪',
    description: 'Disclose how your site uses cookies and how users can control them.',
    fields: [
      { key: 'companyName', label: 'Company / Website Name', placeholder: 'Acme Corp', required: true },
      { key: 'websiteUrl', label: 'Website URL', placeholder: 'https://acme.com', required: true },
      { key: 'contactEmail', label: 'Contact Email', placeholder: 'privacy@acme.com', required: true, type: 'email' },
      { key: 'cookieTypes', label: 'Types of Cookies Used', type: 'textarea', placeholder: 'Session cookies, analytics cookies (Google Analytics), preference cookies…', wide: true, required: true },
      { key: 'cookieDuration', label: 'Cookie Duration', type: 'textarea', placeholder: 'Session cookies expire on browser close; analytics cookies persist for 2 years…', wide: true },
      { key: 'consentMechanism', label: 'Consent Mechanism', type: 'select', options: [{ value: 'banner', label: 'Cookie consent banner' }, { value: 'settings', label: 'Browser/account settings' }, { value: 'none', label: 'No explicit consent (essential only)' }] },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', required: true },
    ],
  },
  {
    id: 'disclaimer',
    name: 'Disclaimer',
    icon: '⚠️',
    description: 'Limit liability and set expectations for the accuracy of your content.',
    fields: [
      { key: 'companyName', label: 'Company / Website Name', placeholder: 'Acme Corp', required: true },
      { key: 'websiteUrl', label: 'Website URL', placeholder: 'https://acme.com', required: true },
      { key: 'contactEmail', label: 'Contact Email', placeholder: 'info@acme.com', required: true, type: 'email' },
      { key: 'contentType', label: 'Type of Content', type: 'select', options: [{ value: 'general', label: 'General information' }, { value: 'financial', label: 'Financial / investment information' }, { value: 'medical', label: 'Medical / health information' }, { value: 'legal', label: 'Legal information' }], required: true },
      { key: 'disclaimerDetails', label: 'Additional Disclaimer Details', type: 'textarea', placeholder: 'Our content is for informational purposes only and should not be considered professional advice…', wide: true },
      { key: 'externalLinks', label: 'Does your site link to external sites?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', required: true },
    ],
  },
  {
    id: 'refund-policy',
    name: 'Refund Policy',
    icon: '💳',
    description: 'Clearly communicate your refund, return, and cancellation rules.',
    fields: [
      { key: 'companyName', label: 'Company / Website Name', placeholder: 'Acme Corp', required: true },
      { key: 'websiteUrl', label: 'Website URL', placeholder: 'https://acme.com', required: true },
      { key: 'contactEmail', label: 'Contact Email', placeholder: 'billing@acme.com', required: true, type: 'email' },
      { key: 'refundWindow', label: 'Refund Window (days)', placeholder: '30', type: 'number', required: true },
      { key: 'productType', label: 'Product / Service Type', type: 'select', options: [{ value: 'digital', label: 'Digital product / download' }, { value: 'saas', label: 'SaaS / subscription' }, { value: 'physical', label: 'Physical product' }, { value: 'service', label: 'Service / consulting' }], required: true },
      { key: 'refundConditions', label: 'Conditions for Refund', type: 'textarea', placeholder: 'Product must be unused; request must be submitted within 30 days of purchase…', wide: true },
      { key: 'nonRefundable', label: 'Non-Refundable Items', type: 'textarea', placeholder: 'Gift cards, downloadable content after download, custom orders…', wide: true },
      { key: 'processTime', label: 'Processing Time', placeholder: '5–7 business days' },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', required: true },
    ],
  },
  {
    id: 'eula',
    name: 'EULA',
    icon: '💿',
    description: 'End User License Agreement for software or digital products.',
    fields: [
      { key: 'companyName', label: 'Company Name', placeholder: 'Acme Corp', required: true },
      { key: 'productName', label: 'Product / Software Name', placeholder: 'Acme Pro', required: true },
      { key: 'websiteUrl', label: 'Website URL', placeholder: 'https://acme.com', required: true },
      { key: 'contactEmail', label: 'Contact Email', placeholder: 'legal@acme.com', required: true, type: 'email' },
      { key: 'country', label: 'Governing Law', placeholder: 'Delaware, United States', required: true },
      { key: 'licenseType', label: 'License Type', type: 'select', options: [{ value: 'single', label: 'Single-user license' }, { value: 'multi', label: 'Multi-user / team license' }, { value: 'enterprise', label: 'Enterprise license' }] },
      { key: 'restrictions', label: 'Usage Restrictions', type: 'textarea', placeholder: 'No reverse engineering, no redistribution, no use in competing products…', wide: true },
      { key: 'effectiveDate', label: 'Effective Date', type: 'date', required: true },
    ],
  },
  {
    id: 'about-us',
    name: 'About Us',
    icon: '🏢',
    description: 'A professional About Us page that tells your company story, mission, and team.',
    fields: [
      { key: 'companyName', label: 'Company / Brand Name', placeholder: 'Acme Corp', required: true },
      { key: 'websiteUrl', label: 'Website URL', placeholder: 'https://acme.com', required: true },
      { key: 'contactEmail', label: 'Contact Email', placeholder: 'hello@acme.com', required: true, type: 'email' },
      { key: 'foundedYear', label: 'Year Founded', placeholder: '2019', type: 'number' },
      { key: 'headquartersLocation', label: 'Headquarters Location', placeholder: 'San Francisco, CA' },
      { key: 'companyType', label: 'Company Type', type: 'select', options: [{ value: 'startup', label: 'Startup / Early-stage' }, { value: 'smb', label: 'Small & Medium Business' }, { value: 'enterprise', label: 'Enterprise / Corporation' }, { value: 'nonprofit', label: 'Non-profit / NGO' }, { value: 'freelance', label: 'Freelancer / Solo founder' }], required: true },
      { key: 'tagline', label: 'Company Tagline / Slogan', placeholder: 'Building the future of work.', wide: true },
      { key: 'missionStatement', label: 'Mission Statement', type: 'textarea', placeholder: 'Our mission is to make project management effortless for every team on the planet…', wide: true, required: true, hint: 'Describe the core purpose or "why" behind your company.' },
      { key: 'whatWeDo', label: 'What We Do', type: 'textarea', placeholder: 'We build cloud-based tools that help teams collaborate, track progress, and ship faster…', wide: true, required: true, hint: 'Explain your products, services, or area of focus.' },
      { key: 'ourStory', label: 'Our Story', type: 'textarea', placeholder: 'Acme Corp was founded in 2019 when our two co-founders grew frustrated with existing solutions…', wide: true, hint: 'Share how and why the company was started.' },
      { key: 'teamSize', label: 'Team Size', type: 'select', options: [{ value: '1', label: 'Just me (solo)' }, { value: '2-10', label: '2–10 people' }, { value: '11-50', label: '11–50 people' }, { value: '51-200', label: '51–200 people' }, { value: '200+', label: '200+ people' }] },
      { key: 'coreValues', label: 'Core Values', type: 'textarea', placeholder: 'Transparency, customer obsession, continuous learning, diversity & inclusion…', wide: true, hint: 'List the values that guide how your team works.' },
      { key: 'socialLinks', label: 'Social Media Links', type: 'textarea', placeholder: 'Twitter: https://twitter.com/acme\nLinkedIn: https://linkedin.com/company/acme', wide: true, hint: 'Optional — list any relevant social or community links.' },
    ],
  },
  {
    id: 'contact-us',
    name: 'Contact Us',
    icon: '✉️',
    description: 'A clear and welcoming Contact Us page with your contact details and support channels.',
    fields: [
      { key: 'companyName', label: 'Company / Brand Name', placeholder: 'Acme Corp', required: true },
      { key: 'websiteUrl', label: 'Website URL', placeholder: 'https://acme.com', required: true },
      { key: 'generalEmail', label: 'General Enquiries Email', placeholder: 'hello@acme.com', required: true, type: 'email' },
      { key: 'supportEmail', label: 'Support Email', placeholder: 'support@acme.com', type: 'email', hint: 'Leave blank to use the general email for all enquiries.' },
      { key: 'phoneNumber', label: 'Phone Number', placeholder: '+1 (555) 000-0000', hint: 'Optional — leave blank to omit from the page.' },
      { key: 'physicalAddress', label: 'Physical / Mailing Address', type: 'textarea', placeholder: '123 Market Street, Suite 400\nSan Francisco, CA 94105\nUnited States', wide: true, hint: 'Optional — include if you receive physical mail or have a public office.' },
      { key: 'officeHours', label: 'Office / Support Hours', placeholder: 'Monday–Friday, 9 am – 6 pm PT', hint: 'Optional — let visitors know when to expect a response.' },
      { key: 'responseTime', label: 'Typical Response Time', placeholder: 'Within 1 business day', hint: 'Set expectations for how quickly you reply.' },
      { key: 'supportChannels', label: 'Additional Support Channels', type: 'textarea', placeholder: 'Live chat: available on our website\nHelp centre: https://help.acme.com\nTwitter DMs: @acmesupport', wide: true, hint: 'List any other ways users can reach you.' },
      { key: 'contactFormNote', label: 'Contact Form Note', type: 'textarea', placeholder: 'Please include your order number or account email so we can assist you faster.', wide: true, hint: 'Optional — any extra instructions for people reaching out.' },
    ],
  },
]
